const recipeTypes = [
    'Lunch',
    'Dinner',
    'Snack',
    'Teatime',
    'Alcohol-cocktail',
    'Biscuits and cookies',
    'Bread',
    'Cereals',
    'Condiments and sauces',
    'Drinks',
    'Desserts',
    'Egg',
    'Main course',
    'Omelet',
    'Pancake',
    'Preps',
    'Preserve',
    'Salad',
    'Sandwiches',
    'Soup',
    'Starter',
    'American',
    'Asian',
    'British',
    'Caribbean',
    'Central Europe',
    'Chinese',
    'Eastern Europe',
    'French',
    'Indian',
    'Italian',
    'Japanese',
    'Kosher',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'South American',
    'South East Asian',
    'balanced',
    'high-fiber',
    'high-protein',
    'low-carb',
    'low-fat',
    'low-sodium',
    'alcohol-free',
    'immuno-supportive',
    'celery-free',
    'crustacean-free',
    'dairy-free',
    'egg-free',
    'fish-free',
    'fodmap-free',
    'gluten-free',
    'keto-friendly',
    'kidney-friendly',
    'kosher',
    'potassium',
    'lupine-free',
    'mustard-free',
    'low-fat-abs',
    'No-oil-added',
    'low-sugar',
    'paleo',
    'peanut-free',
    'pecatarian',
    'pork-free',
    'red-meat-free',
    'sesame-free',
    'shellfish-free',
    'soy-free',
    'sugar-conscious',
    'tree-nut-free',
    'vegan',
    'vegetarian',
    'wheat-free'
]

export default recipeTypes;